### ISSUE TITLE
Feature request: Improvement for user configuration

### ISSUE THREAD

**Issue by YisusChrist** [Zaloog/kanban-python#6]
Consider using tools like [platformdirs](https://github.com/platformdirs/platformdirs) to save the config file (and many other files) in standard directories with multi-platform support. It is very important to follow [XDG](https://wiki.archlinux.org/title/XDG_Base_Directory) when placing files inside other people's systems, that way the information is well organized in the OS. You can see a simple example in this [project](https://github.com/YisusChrist/iltransfer/tree/main/iltransfer) of mine where I also create config files using configparse (and also log files) with the help of platformdirs to automatically retrieve the correct path that should store those files.

It is really easy to implement and the benefit is huge for the open-source community!

**Comment by Zaloog** [comment]
Hi,
thanks for info and also providing helpful links.

So would it then be best practice to store the `pykanban.ini` in `user_config_dir` and the `pykanban.json` data for the boards
in `user_data_dir`?

**Comment by YisusChrist** [comment]
Exactly, that would be a nice way to organize the files. By the way, maybe it would be simpler to avoid creating folders for different boards and just create the JSON files with the name of the boards.

That wat instead of having:
```
└───kanban_boards
    ├───Test Board
    │       pykanban.json
    │
    └───test-board
            pykanban.json
```

You could just have:
```
└───kanban_boards
    ├───Test Board.json
    └───test-boardjson
```

That way could be easier to manage the different user boards.
Either way the app looks nice, I love the rich usage!

**Comment by Zaloog** [comment]
Ye I was also thinking about different ways of structuring that [see here](https://github.com/Zaloog/kanban-python/blob/f75cb8db2fa23a51876a69a3e23dbbc7e4620243/src/kanban_python/controls.py#L55-L58)

The reason why I decided to create board specific folders is because I also plan to create some reports/statistics on task completion/progress in the future, which I want to store in the board folder next to the tasks.

I will change to the `XDG` convention after Ive completed the automated scanner to add tasks.
Thanks again forthe helpful feedback and ressources.

Glad you like the app :)

**Comment by Zaloog** [comment]
@YisusChrist  Done :)

**Comment by YisusChrist** [comment]
I checked it and it looks nice. I love the way you organized the new constants module. Congratulations!

**Comment by Zaloog** [comment]
Thank you @YisusChrist 
Like I Said, the Ressources you provided were a great Help and I learned Something New. Thanks again for that :) 

Also Improved configuring the settings and added an Option to Show Tasks now with todays newest Release.
